@startuml
'https://plantuml.com/class-diagram


Pizza <|-- CheessPizza
Pizza <|-- PepperPizza
Pizza <|-- GreekPizza

SimpleFactory o-- CheessPizza
SimpleFactory o-- PepperPizza
SimpleFactory o-- GreekPizza

OrderPizza o-- SimpleFactory
OrderPizza2 o-- SimpleFactory


class Pizza {
prepare():void
bake():void
cut():void
box():void
}



@enduml