@startuml
'https://plantuml.com/class-diagram



Client -- AbstractProduct
Client -- Factory

AbstractProduct <|-- Product2
AbstractProduct <|-- Product1

Product1 <.. Factory
Product2 <.. Factory

class Factory {
CreateProduct1(): AbstractProduct
CreateProduct2(): AbstractProduct
}


@enduml